services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
      image: postgres:15-alpine
      expose:
        - "4596"
      volumes:
        - ./db/postgresql:/var/lib/postgresql
      command: -p 4596
      env_file:
        - db.env